name: app

on:
  push:
    branches: [main, "feature/**"]
  pull_request:
    branches: [main, "feature/**"]
  workflow_dispatch:

jobs:
  build:
    name: Build App
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x, 18.x]

    defaults:
      run:
        working-directory: app

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - run: yarn install --ignore-engines
      #- run: npm run check:prettier
      #- run: npm run check:lint
      - run: yarn run build
      #- run: npm test
